export const environment = {
  production: true,
  ajax_dir: 'https://community.establishmindfulness.com/assets/cfm',
  host: 'https://community.establishmindfulness.com',
  cf_dir: 'assets/cfm',
  allowMultipleLikesPerUser: 0,
  title: 'Establish Mindfulness',
  htmlTitle: 'Establish Mindfulness S.P.A',
  logoSrc: 'assets/images/logo.png',
  debugComponentLoadingOrder: false,
  port: '',
  maxcontentlength: 500000,
  tinymcearticlemaximages: 2,
  tinymcearticlemaxwordcount: 680,
  articledescriptionmaxcharcount: 1000,
  openToolbarCommentsPanel: true,
  useRestApi: true,
  restApiURLReWrite: true,
  apiDocumentationUrl: 'https://community.establishmindfulness.com/assets/cfm/components/restAPiService.cfm',
  apiEndpointUrl: 'https://community.establishmindfulness.com/assets/cfm/rest/api/v1/',
  maxCommentInputLength: 140,
  catalogRouterAlias: 'stories',
  uploadRouterAlias: 'upload-story',
  maxcategoryeditnamelength: 30,
  adZoneEnable: true,
  adZoneMaxAdverts: 4,
  adZoneMinImages: 4,
  articleDescriptionCardDisplayLength: 250,
  googleRecaptchaSiteKey: '6LeoNp0UAAAAAKvqhb08rV2BLdBp6h3hgHTGDopU',
  recaptchaType: 'custom',
  customRecaptchaRotationMax: 0,
  customRecaptchaStrLength: 4,
  agGridPaginationPageSize: 10,
  agGridRowHeight: 35,
  imageMediumSuffix: 'preview',
  imageMediumEnabled: true,
  lazyLoadImages: true,
  addRemoveHighlightWaypoints: false,
  cardShowAvatar: false,
  adminDashboardWaypointsEnabled: false
};
